apiVersion: v1
kind: Namespace
metadata:
  name: django

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: django
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: madhur17/dockerbuild:latest
          name: django
          ports:
            - containerPort: 8001
              name: gunicorn

---

apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: django
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8001
      targetPort: 8001
