apiVersion: v1
kind: Namespace
metadata:
  name: dotnet

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: dotnet
  labels:
    app: dotnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
        - image: madhur17/dotnet:latest
          name: dotnet
          ports:
            - containerPort: 80
              name: dotnet

---

apiVersion: v1
kind: Service
metadata:
  name: dotnet
  namespace: dotnet
  labels:
    app: dotnet
spec:
  type: NodePort
  selector:
    app: dotnet
  ports:
    - port: 80
      targetPort: 80


